In [1]:
import torch
import numpy as np

## Tensor 생성

In [2]:
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6]) # real value
print(t)
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [3]:
torch.manual_seed(2022) # 동일한 랜덤 값을 사용할 숫 있도록 해줌

x = torch.rand(2, 3) # 0~1사이의 숫자를 랜덤으로 반환
print(x, '\n')

x = torch.randint(10, size=(2, 3)) # 지정한 벙위내 숫자를 랜덤으로 반환
print(x, '\n')

x = torch.randn(2, 3) # N(0, 1)인 Gaussuian 분포를 따르는 수를 런덤 반환
print(x, '\n')

x = torch.zeros(2, 3) # 입력한 size에 맞는 0을 생성
print(x, '\n')

x = torch.ones(2, 3) # 입력한 size에 맞는 1을 생성
print(x)

tensor([[0.3958, 0.9219, 0.7588],
        [0.3811, 0.0262, 0.3594]]) 

tensor([[4, 5, 4],
        [6, 8, 2]]) 

tensor([[-2.3113,  1.6352,  2.0614],
        [-0.2542, -1.5118, -1.2799]]) 

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:
# torch.arange(start, end, step=1) -> [start, end] with step
x = torch.arange(0, 3, 0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [5]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## List, Numpy => Tensor로 변환

In [6]:
# list로 부터 2x3 텐서 생성
x_list = [[1, 2, 3], [4, 5, 6]]
x = torch.Tensor(x_list)
print(x, '\n')

# numpy array로 부터 2x3 텐서 생성
x_numpy = np.array([[1, 2, 3], [4, 5, 6]])
x = torch.Tensor(x_numpy)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

tensor([[1., 2., 3.],
        [4., 5., 6.]])


## Tensor 크기 변경

In [7]:
 x = np.array([[[0, 1, 2],
                [3, 4 ,5]],
               
               [[6, 7, 8],
                [9, 10, 11]]])

x = torch.Tensor(x)
print(f"{x}, \n\nshape:{x.size()}")

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]]), 

shape:torch.Size([2, 2, 3])


In [8]:
# view

tensor_x = x.view(-1, 3)
print(f"{tensor_x}, \n\nshape:{tensor_x.size()}")

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]]), 

shape:torch.Size([4, 3])


In [9]:
# reshape

tensor_x = x.reshape(-1, 2)
print(f"{tensor_x}, \n\nshape:{tensor_x.size()}")

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]]), 

shape:torch.Size([6, 2])


## Tensor 차원 추가 및 삭제

In [10]:
# squeeze(rank를 줄여주는 기능)
x1 = torch.FloatTensor(10, 1, 3, 1, 4)
print(x1.size(), '\n')

x2 = x1.squeeze()
print(x2.size())

torch.Size([10, 1, 3, 1, 4]) 

torch.Size([10, 3, 4])


In [11]:
# unsqueeze(rank를 늘려주는 기능)
x1 = torch.FloatTensor(10, 3, 4)
print(x1.size(), '\n')

x2 = x1.unsqueeze(dim=1) # torch.unsuqeeze(x1, dim=1)
print(x2.size())

torch.Size([10, 3, 4]) 

torch.Size([10, 1, 3, 4])


## Tensor 합치기

In [12]:
torch.manual_seed(2022)
x = torch.randint(10, size=(2, 3))
y = torch.randint(10, size=(2, 3))

print(f"x = \n{x}")
print(f"y = \n{y}\n")

z = torch.cat([x, y], dim=0)
print(f"z = \n{z}")

x = 
tensor([[1, 0, 3],
        [6, 9, 7]])
y = 
tensor([[4, 5, 4],
        [6, 8, 2]])

z = 
tensor([[1, 0, 3],
        [6, 9, 7],
        [4, 5, 4],
        [6, 8, 2]])


## 평균, 분산 구하기

In [13]:
x = torch.FloatTensor([1, 100])

print(x)
print(f"mean:{x.mean()}")
print(f"variance:{x.var()}")

tensor([  1., 100.])
mean:50.5
variance:4900.5


## Tensor 인덱싱_2dim

In [14]:
z

tensor([[1, 0, 3],
        [6, 9, 7],
        [4, 5, 4],
        [6, 8, 2]])

In [15]:
z[3]

tensor([6, 8, 2])

In [16]:
z[0, 1]

tensor(0)

In [17]:
z[:, 1]

tensor([0, 9, 5, 8])

In [18]:
z[-1]

tensor([6, 8, 2])

In [19]:
z[:, :-1]

tensor([[1, 0],
        [6, 9],
        [4, 5],
        [6, 8]])

In [20]:
z[2:, :]

tensor([[4, 5, 4],
        [6, 8, 2]])

## ## Tensor 인덱싱_3dim

In [21]:
x = torch.randint(10, size=(2, 3, 4))
print(x)
print(f"\nshape:{x.size()}")

tensor([[[7, 9, 1, 7],
         [5, 9, 2, 6],
         [2, 3, 6, 7]],

        [[0, 2, 6, 9],
         [2, 2, 0, 7],
         [0, 5, 4, 4]]])

shape:torch.Size([2, 3, 4])


In [22]:
x[:, 2, :]

tensor([[2, 3, 6, 7],
        [0, 5, 4, 4]])

In [23]:
x[:, 0, :-1]

tensor([[7, 9, 1],
        [0, 2, 6]])